# Generated by Django 3.1.3 on 2022-09-29 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaincenter',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complain', to='pbs.zonal'),
        ),
        migrations.AlterField(
            model_name='fider',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fider', to='pbs.complaincenter'),
        ),
        migrations.AlterField(
            model_name='zonal',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonal', to='pbs.pbs'),
        ),
    ]
