# Generated by Django 3.1.3 on 2022-10-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='pbs.fider'),
        ),
    ]
