# Generated by Django 3.1.3 on 2022-10-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0005_auto_20221003_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
