# Generated by Django 3.1.3 on 2022-10-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0006_auto_20221003_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fider',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
