# Generated by Django 3.1.3 on 2022-10-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0007_auto_20221003_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='fider',
            name='fiderNo',
            field=models.IntegerField(default=2),
        ),
    ]
