# Generated by Django 3.1.3 on 2022-10-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0009_auto_20221003_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='solved_at',
            field=models.DateTimeField(),
        ),
    ]
