# Generated by Django 3.1.3 on 2022-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0011_auto_20221003_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='fider',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
