# Generated by Django 3.1.3 on 2022-10-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0012_auto_20221003_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fider',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
