# Generated by Django 3.1.3 on 2022-10-07 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbs', '0015_auto_20221003_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='fider',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fider',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='complaincenter',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='pbs.subzonal'),
        ),
        migrations.AlterField(
            model_name='fider',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='pbs.complaincenter'),
        ),
        migrations.AlterField(
            model_name='report',
            name='solved_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subzonal',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='pbs.zonal'),
        ),
        migrations.AlterField(
            model_name='zonal',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='pbs.pbs'),
        ),
    ]
